[build]
  publish = "dist"
  command = "chmod +x ./netlify-build.sh && ./netlify-build.sh"
  # Using a shell script to bypass TypeScript issues

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
